/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

/**
 *
 * @author Léo - Xande
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaPrincipal = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuLocacao = new javax.swing.JMenu();
        jMenuAlugar = new javax.swing.JMenu();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuAtor = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuFilme = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Locadora");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanelTelaPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/a70ba275-b060-4345-a1f0-793b29d8e501.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanelTelaPrincipalLayout = new javax.swing.GroupLayout(jPanelTelaPrincipal);
        jPanelTelaPrincipal.setLayout(jPanelTelaPrincipalLayout);
        jPanelTelaPrincipalLayout.setHorizontalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanelTelaPrincipalLayout.setVerticalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelLogo)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jMenuLocacao.setText("Locação");
        jMenuLocacao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuAlugar.setText("Alugar");
        jMenuAlugar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuLocacao.add(jMenuAlugar);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuLocacao.add(jMenuConsultar);

        jMenuBarTelaPrincipal.add(jMenuLocacao);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuAtor.setText("Ator");
        jMenuAtor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuCadastro.add(jMenuAtor);

        jMenuCliente.setText("Cliente");
        jMenuCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuCadastro.add(jMenuCliente);

        jMenuFilme.setText("Filme");
        jMenuFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuCadastro.add(jMenuFilme);

        jMenuItem.setText("Item");
        jMenuItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuCadastro.add(jMenuItem);

        jMenuBarTelaPrincipal.add(jMenuCadastro);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBarTelaPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenu jMenuAlugar;
    private javax.swing.JMenu jMenuAtor;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenu jMenuFilme;
    private javax.swing.JMenu jMenuItem;
    private javax.swing.JMenu jMenuLocacao;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
